<?php
/**
 * Map For Special Content Block.
 *
 * @package H-Code
 */
?>
<?php
/*-----------------------------------------------------------------------------------*/
/* Content Block */
/*-----------------------------------------------------------------------------------*/

vc_map( array(
      'name' => __( 'Special Content Block', 'hcode-addons' ),
      'base' => 'hcode_content_block',
      'category' => 'H-Code',
      'icon' => 'far fa-list-alt h-code-shortcode-icon',
      'description' => __( 'Create a special content block', 'hcode-addons' ),
      'params' => array(
        array(
          'type' => 'dropdown',
          'admin_label' => true,
          'class' => '',
          'heading' => __('Content Block Style', 'hcode-addons'),
          'param_name' => 'hcode_block_premade_style',
          'value' => array(__('Select Content Block Style', 'hcode-addons') => '',
                           __('Block Style1', 'hcode-addons') => 'block-1',
                           __('Block Style2', 'hcode-addons') => 'block-2',
                           __('Block Style3', 'hcode-addons') => 'block-3',
                           __('Block Style4', 'hcode-addons') => 'block-4',
                           __('Block Style5', 'hcode-addons') => 'block-5',
                           __('Block Style6', 'hcode-addons') => 'block-6',
                           __('Block Style7', 'hcode-addons') => 'block-7',
                           __('Block Style8', 'hcode-addons') => 'block-8',
                           __('Block Style9', 'hcode-addons') => 'block-9',
                           __('Block Style10', 'hcode-addons') => 'block-10',
                           __('Block Style11', 'hcode-addons') => 'block-11',
                           __('Block Style12', 'hcode-addons') => 'block-12',
                           __('Block Style13', 'hcode-addons') => 'block-13',
                           __('Block Style14', 'hcode-addons') => 'block-14',
                           __('Block Style15', 'hcode-addons') => 'block-15',
                           __('Block Style16', 'hcode-addons') => 'block-16',
                           __('Block Style17', 'hcode-addons') => 'block-17',
                           __('Block Style18', 'hcode-addons') => 'block-18',
                           __('Block Style19', 'hcode-addons') => 'block-19',
                           __('Block Style20', 'hcode-addons') => 'block-20',
                           __('Block Style21', 'hcode-addons') => 'block-21',
                           __('Block Style22', 'hcode-addons') => 'block-22',
                           __('Block Style23', 'hcode-addons') => 'block-23',
                           __('Block Style24', 'hcode-addons') => 'block-24',
                           __('Block Style25', 'hcode-addons') => 'block-25',
                           __('Block Style26', 'hcode-addons') => 'block-26',
                           __('Block Style27', 'hcode-addons') => 'block-27',
                           __('Block Style28', 'hcode-addons') => 'block-28',
                           __('Block Style29', 'hcode-addons') => 'block-29',
                           __('Block Style30', 'hcode-addons') => 'block-30',
                           __('Block Style31', 'hcode-addons') => 'block-31',
                           __('Block Style32', 'hcode-addons') => 'block-32',
                           __('Block Style33', 'hcode-addons') => 'block-33',
                           __('Block Style34', 'hcode-addons') => 'block-34',
                           __('Block Style35', 'hcode-addons') => 'block-35',
                           __('Block Style36', 'hcode-addons') => 'block-36',
                           __('Block Style37', 'hcode-addons') => 'block-37',
                           __('Block Style38', 'hcode-addons') => 'block-38',
                           __('Block Style39', 'hcode-addons') => 'block-39',
                           __('Block Style40', 'hcode-addons') => 'block-40',
                           __('Block Style41', 'hcode-addons') => 'block-41',
                           __('Block Style42', 'hcode-addons') => 'block-42',
                           __('Block Style43', 'hcode-addons') => 'block-43',
                           __('Block Style44', 'hcode-addons') => 'block-44',
                           __('Block Style45', 'hcode-addons') => 'block-45',
                           __('Block Style46', 'hcode-addons') => 'block-46',
                           __('Block Style47', 'hcode-addons') => 'block-47',
                           __('Block Style48', 'hcode-addons') => 'block-48',
                           __('Block Style49', 'hcode-addons') => 'block-49',
                           __('Block Style50', 'hcode-addons') => 'block-50',
                           __('Block Style51', 'hcode-addons') => 'block-51',
                           __('Block Style52', 'hcode-addons') => 'block-52',
                           __('Block Style53', 'hcode-addons') => 'block-53',
                           __('Block Style54', 'hcode-addons') => 'block-54',
                           __('Block Style55', 'hcode-addons') => 'block-55',
                          ),
        ),
        array(
          'type' => 'hcode_preview_image',
          'heading' => __('Select pre-made style for block', 'hcode-addons'),
          'param_name' => 'hcode_block_preview_image',
        ),
        array(
            'type' => 'hcode_custom_switch_option',
            'class' => '',
            'heading' => __('Set Block Position Right', 'hcode-addons'),
            'param_name' => 'hcode_block_position_right',
            'value' => array(__('NO', 'hcode-addons') => '0', 
                             __('YES', 'hcode-addons') => '1'
                            ),
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-46') ),
        ),
        array(
          'type' => 'attach_image',
          'heading' => __('Block Image', 'hcode-addons' ),
          'param_name' => 'hcode_block_image',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-1','block-4','block-5','block-7','block-18','block-19','block-22','block-25','block-26','block-27','block-29','block-33','block-34','block-35','block-36','block-37','block-39','block-40','block-42','block-43','block-44','block-49','block-50','block-51','block-53') ),
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'class' => '',
          'heading' => __('Set Image Position', 'hcode-addons'),
          'param_name' => 'hcode_image_position',
          'value' => array(__('Right', 'hcode-addons') => '0', 
                           __('Left', 'hcode-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-19') ),
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'heading' => __('Custom Icon', 'hcode-addons'),
          'param_name' => 'custom_icon',
          'value' => array(__('NO', 'hcode-addons') => '0',
                           __('YES', 'hcode-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-2', 'block-20', 'block-13', 'block-24', 'block-30', 'block-31', 'block-32','block-54','block-55') ),
        ),
        array(
          'type' => 'attach_image',
          'heading' => __('Custom Icon Image', 'hcode-addons'),
          'param_name' => 'custom_icon_image',
          'dependency' => array( 'element' => 'custom_icon', 'value' => '1' ),
          'description' => __( 'Recommended size: 60px X 60px', 'hcode-addons' ),
        ),
        array(
          'type' => 'hcode_icon',
          'heading' => __('Icon', 'hcode-addons' ),
          'param_name' => 'hcode_block_icon_list',
          'dependency' => array( 'element' => 'custom_icon', 'value' => '0' ),
        ),
        array(
          'type' => 'textfield',
          'admin_label' => true,
          'heading' => __( 'Block Title', 'hcode-addons' ),
          'param_name' => 'hcode_block_title',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-1','block-2','block-3','block-4','block-5','block-6','block-7','block-8','block-9','block-10','block-11', 'block-12', 'block-13','block-14','block-15', 'block-16', 'block-17','block-19','block-20','block-21', 'block-22', 'block-23', 'block-24','block-25','block-26','block-27','block-28','block-29', 'block-30', 'block-31', 'block-32','block-34','block-35','block-36','block-37','block-38','block-39','block-40','block-41','block-42','block-43','block-44', 'block-45', 'block-46', 'block-47', 'block-48','block-49','block-50','block-51','block-52','block-53','block-54','block-55') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __('Link', 'hcode-addons' ),
          'param_name' => 'hcode_block_title_link',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-1','block-2','block-3','block-4','block-5','block-6','block-7','block-8','block-10', 'block-12', 'block-13','block-15', 'block-16', 'block-17','block-19','block-20','block-21', 'block-22', 'block-23', 'block-24','block-25','block-26','block-27','block-28','block-29', 'block-30', 'block-31', 'block-32','block-35','block-37','block-38','block-39','block-40','block-41','block-42','block-43','block-44', 'block-45', 'block-47', 'block-48','block-51','block-52','block-53','block-54','block-55') ),
        ),
        array(
          'type' => 'dropdown',
          'heading' => __('Link Target', 'hcode-addons' ),
          'param_name' => 'hcode_block_title_link_target',
          'value' => array(__('Select Link Target', 'hcode-addons') => '',
                           __('Same window / tab', 'hcode-addons') => '_self', 
                           __('New Window / tab', 'hcode-addons') => '_blank',
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-1','block-2','block-3','block-4','block-5','block-6','block-7','block-8','block-10', 'block-12', 'block-13','block-15', 'block-16', 'block-17','block-19','block-20','block-21', 'block-22', 'block-23', 'block-24','block-25','block-26','block-27','block-28','block-29', 'block-30', 'block-31', 'block-32','block-35','block-37','block-38','block-39','block-40','block-41','block-42','block-43','block-44', 'block-45', 'block-47', 'block-48','block-51','block-52','block-53','block-54','block-55') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Block Subtitle', 'hcode-addons' ),
          'param_name' => 'hcode_block_subtitle',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-3','block-4','block-8','block-9','block-10','block-11','block-20','block-25','block-26','block-27','block-29','block-36','block-37','block-39', 'block-45', 'block-47','block-49','block-50') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Block Number', 'hcode-addons' ),
          'param_name' => 'hcode_block_number',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-20','block-21', 'block-23','block-28','block-44', 'block-48') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Block Hover Title', 'hcode-addons' ),
          'param_name' => 'hcode_block_hover_title',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-20') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Block Hover URL', 'hcode-addons' ),
          'param_name' => 'hcode_block_hover_url',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-20') ),
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'class' => '',
          'heading' => __( 'Block Hover Target Blank', 'hcode-addons'),
          'param_name' => 'hcode_block_hover_target_blank',
          'value' => array(__('NO', 'hcode-addons') => '0', 
                           __('YES', 'hcode-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-20') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Block Price', 'hcode-addons' ),
          'param_name' => 'hcode_block_price',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-43') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Block Title URL', 'hcode-addons' ),
          'param_name' => 'hcode_block_title_url',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-9','block-34','block-36') ),
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'class' => '',
          'heading' => __( 'Default Cursor', 'hcode-addons'),
          'param_name' => 'hcode_block_default_cursor',
          'value' => array(__('NO', 'hcode-addons') => '0', 
                           __('YES', 'hcode-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-34') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Block Discount off Text', 'hcode-addons' ),
          'param_name' => 'hcode_block_gifts_off',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-9') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Event Date', 'hcode-addons' ),
          'param_name' => 'hcode_block_event_date',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-30') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Event Time', 'hcode-addons' ),
          'param_name' => 'hcode_block_event_time',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-30') ),
        ),
        array(
          'type' => 'textarea_html',
          'heading' => __( 'Content', 'hcode-addons' ),
          'param_name' => 'content',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-1','block-2','block-3','block-4','block-5','block-6','block-8','block-11', 'block-12', 'block-13','block-15', 'block-16', 'block-17', 'block-18','block-19','block-21','block-22', 'block-23', 'block-24','block-26','block-28','block-29', 'block-30','block-37','block-38','block-39','block-40','block-42','block-43','block-44', 'block-46', 'block-47', 'block-48','block-51','block-53','block-54') ),
        ),
        array(
        'type' => 'dropdown',
        'heading' => __('Stars', 'hcode-addons'),
        'param_name' => 'hcode_stars',
        'admin_label' => true,
        'value' => array(__('Select Stars', 'hcode-addons') => '',
                         __('Star 1', 'hcode-addons') => '1',
                         __('Star 2', 'hcode-addons') => '2', 
                         __('Star 3', 'hcode-addons') => '3',
                         __('Star 4', 'hcode-addons') => '4',
                         __('Star 5', 'hcode-addons') => '5',
                        ),
        'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-36','block-37') ),
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'class' => '',
          'heading' => __('Show Image Position', 'hcode-addons'),
          'param_name' => 'hcode_block_image_position',
          'value' => array(__('Right', 'hcode-addons') => '0', 
                           __('Left', 'hcode-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-4') ),
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'class' => '',
          'heading' => __('Show Strike Through', 'hcode-addons'),
          'param_name' => 'hcode_block_strike_through',
          'value' => array(__('NO', 'hcode-addons') => '0', 
                           __('YES', 'hcode-addons') => '1'
                          ),
          'std' => '1',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-23') ),
        ),
        array(
            'type' => 'hcode_custom_switch_option',
            'class' => '',
            'heading' => __('Show Separator', 'hcode-addons'),
            'param_name' => 'hcode_block_show_separator',
            'value' => array(__('NO', 'hcode-addons') => '0', 
                             __('YES', 'hcode-addons') => '1'
                            ),
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-1','block-4','block-8','block-22', 'block-24','block-29','block-30','block-39','block-40','block-43','block-46','block-50','block-52') ),
        ),
        array(
          'type'        => 'vc_link',
          'heading'     => __('Button Config', 'hcode-addons' ),
          'param_name'  => 'button_config',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-1','block-2','block-4','block-6','block-8', 'block-18','block-30','block-37','block-38','block-39','block-42', 'block-45','block-49') ),
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'class' => '',
          'heading' => __('Add Border', 'hcode-addons'),
          'param_name' => 'hcode_border_class',
          'value' => array(__('NO', 'hcode-addons') => '0', 
                           __('YES', 'hcode-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-33') ),
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'heading' => __('Custom Hover Icon1', 'hcode-addons'),
          'param_name' => 'hcode_block_hover_custom_icon',
          'value' => array(__('NO', 'hcode-addons') => '0',
                           __('YES', 'hcode-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-49') ),
        ),
        array(
          'type' => 'attach_image',
          'heading' => __('Custom Hover Icon1 Image', 'hcode-addons'),
          'param_name' => 'hcode_block_hover_custom_icon_image',
          'dependency' => array( 'element' => 'hcode_block_hover_custom_icon', 'value' => '1' ),
          'description' => __( 'Recommended size: Extra Large - 60px X 60px, Large - 50px X 50px, Medium - 40px X 40px, Small - 25px X 25px, Extra Small - 18px X 18px', 'hcode-addons' ),
        ),
        array(
          'type' => 'hcode_icon',
          'heading' => __('Hover Icon1', 'hcode-addons' ),
          'param_name' => 'hcode_block_hover_icon1',
          'dependency' => array( 'element' => 'hcode_block_hover_custom_icon', 'value' => '0' ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Hover Title1', 'hcode-addons' ),
          'param_name' => 'hcode_block_hover_title1',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-49') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Hover Subtitle1', 'hcode-addons' ),
          'param_name' => 'hcode_block_hover_subtitle1',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-49') ),
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'heading' => __('Custom Hover Icon2', 'hcode-addons'),
          'param_name' => 'hcode_block_hover_custom_icon2',
          'value' => array(__('NO', 'hcode-addons') => '0',
                           __('YES', 'hcode-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-49') ),
        ),
        array(
          'type' => 'attach_image',
          'heading' => __('Custom Hover Icon2 Image', 'hcode-addons'),
          'param_name' => 'hcode_block_hover_custom_icon2_image',
          'dependency' => array( 'element' => 'hcode_block_hover_custom_icon2', 'value' => '1' ),
        ),
        array(
          'type' => 'hcode_icon',
          'heading' => __('Hover Icon2', 'hcode-addons' ),
          'param_name' => 'hcode_block_hover_icon2',
          'dependency' => array( 'element' => 'hcode_block_hover_custom_icon2', 'value' => '0' ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Hover Title2', 'hcode-addons' ),
          'param_name' => 'hcode_block_hover_title2',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-49') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Hover Subtitle2', 'hcode-addons' ),
          'param_name' => 'hcode_block_hover_subtitle2',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-49') ),
        ),
        array(
          'type' => 'textarea',
          'heading' => __( 'Hover Content', 'hcode-addons' ),
          'param_name' => 'hcode_block_hover_content',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-49') ),
        ),
        array(
          'type' => 'textarea',
          'heading' => __( 'Small Title', 'hcode-addons' ),
          'param_name' => 'hcode_block_hover_destinations_small_title',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-50') ),
        ),
        array(
          'type' => 'attach_image',
          'heading' => __('Destinations Image1', 'hcode-addons' ),
          'param_name' => 'hcode_block_hover_destinations_image1',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-50') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Destinations Title1', 'hcode-addons' ),
          'param_name' => 'hcode_block_hover_destinations_title1',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-50') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Destinations Block URL', 'hcode-addons' ),
          'param_name' => 'hcode_block_hover_destinations_url1',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-50') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Destinations SubTitle1', 'hcode-addons' ),
          'param_name' => 'hcode_block_hover_destinations_subtitle1',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-50') ),
        ),
        array(
          'type' => 'attach_image',
          'heading' => __('Destinations Image2', 'hcode-addons' ),
          'param_name' => 'hcode_block_hover_destinations_image2',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-50') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Destinations Title2', 'hcode-addons' ),
          'param_name' => 'hcode_block_hover_destinations_title2',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-50') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Destinations Block URL2', 'hcode-addons' ),
          'param_name' => 'hcode_block_hover_destinations_url2',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-50') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Destinations SubTitle2', 'hcode-addons' ),
          'param_name' => 'hcode_block_hover_destinations_subtitle2',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-50') ),
        ),
        array(
          'type' => 'attach_image',
          'heading' => __('Destinations Image3', 'hcode-addons' ),
          'param_name' => 'hcode_block_hover_destinations_image3',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-50') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Destinations Title3', 'hcode-addons' ),
          'param_name' => 'hcode_block_hover_destinations_title3',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-50') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Destinations Block URL3', 'hcode-addons' ),
          'param_name' => 'hcode_block_hover_destinations_url3',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-50') ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Destinations SubTitle3', 'hcode-addons' ),
          'param_name' => 'hcode_block_hover_destinations_subtitle3',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-50') ),
        ),
        array(
          'type'        => 'vc_link',
          'heading'     => __('Hover Button Config', 'hcode-addons' ),
          'param_name'  => 'hover_button_config',
          'admin_label' => true,
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-49') ),
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'class' => '',
          'heading' => __('Show Telephone', 'hcode-addons'),
          'param_name' => 'hcode_block_telephone',
          'value' => array(__('NO', 'hcode-addons') => '0', 
                           __('YES', 'hcode-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-1') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Telephone Prefix', 'hcode-addons' ),
          'param_name' => 'hcode_block_telephone_prefix',
          'dependency' => array( 'element' => 'hcode_block_telephone', 'value' => array('1') ),
          'value' => 'T.',
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Telephone Number', 'hcode-addons' ),
          'param_name' => 'hcode_block_telephone_number',
          'dependency' => array( 'element' => 'hcode_block_telephone', 'value' => array('1') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Telephone Prefix Color', 'hcode-addons' ),
          'param_name' => 'hcode_telephone_prefix_color',
          'dependency' => array( 'element' => 'hcode_block_telephone', 'value' => array('1') ),
          'group' => 'Other Settings',
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Telephone Number Color', 'hcode-addons' ),
          'param_name' => 'hcode_telephone_number_color',
          'dependency' => array( 'element' => 'hcode_block_telephone', 'value' => array('1') ),
          'group' => 'Other Settings',
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'class' => '',
          'heading' => __('Show Email', 'hcode-addons'),
          'param_name' => 'hcode_block_email',
          'value' => array(__('NO', 'hcode-addons') => '0', 
                           __('YES', 'hcode-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-1') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Email Prefix', 'hcode-addons' ),
          'param_name' => 'hcode_block_email_prefix',
          'dependency' => array( 'element' => 'hcode_block_email', 'value' => array('1') ),
          'value' => 'E.',
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Email Id', 'hcode-addons' ),
          'param_name' => 'hcode_block_email_url',
          'dependency' => array( 'element' => 'hcode_block_email', 'value' => array('1') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Email Prefix Color', 'hcode-addons' ),
          'param_name' => 'hcode_email_prefix_color',
          'dependency' => array( 'element' => 'hcode_block_email', 'value' => array('1') ),
          'group' => 'Other Settings',
        ),
        array(
          'type' => 'colorpicker',
          'class' => '',
          'heading' => __( 'Email Id Color', 'hcode-addons' ),
          'param_name' => 'hcode_email_id_color',
          'dependency' => array( 'element' => 'hcode_block_email', 'value' => array('1') ),
          'group' => 'Other Settings',
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'class' => '',
          'heading' => __('Show Facebook Icon', 'hcode-addons'),
          'param_name' => 'hcode_block_facebook',
          'value' => array(__('NO', 'hcode-addons') => '0', 
                           __('YES', 'hcode-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-29') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Facebook URL', 'hcode-addons' ),
          'param_name' => 'hcode_block_facebook_url',
          'dependency' => array( 'element' => 'hcode_block_facebook', 'value' => array('1') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'class' => '',
          'heading' => __('Show Twitter Icon', 'hcode-addons'),
          'param_name' => 'hcode_block_twitter',
          'value' => array(__('NO', 'hcode-addons') => '0', 
                           __('YES', 'hcode-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-29') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Twitter URL', 'hcode-addons' ),
          'param_name' => 'hcode_block_twitter_url',
          'dependency' => array( 'element' => 'hcode_block_twitter', 'value' => array('1') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'class' => '',
          'heading' => __('Show Google-plus Icon', 'hcode-addons'),
          'param_name' => 'hcode_block_googleplus',
          'value' => array(__('NO', 'hcode-addons') => '0', 
                           __('YES', 'hcode-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-29') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Google-plus URL', 'hcode-addons' ),
          'param_name' => 'hcode_block_googleplus_url',
          'dependency' => array( 'element' => 'hcode_block_googleplus', 'value' => array('1') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'class' => '',
          'heading' => __('Show Dribbble Icon', 'hcode-addons'),
          'param_name' => 'hcode_block_dribbble',
          'value' => array(__('NO', 'hcode-addons') => '0', 
                           __('YES', 'hcode-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-29') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Dribbble URL', 'hcode-addons' ),
          'param_name' => 'hcode_block_dribbble_url',
          'dependency' => array( 'element' => 'hcode_block_dribbble', 'value' => array('1') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'class' => '',
          'heading' => __('Show Youtube Icon', 'hcode-addons'),
          'param_name' => 'hcode_block_youtube',
          'value' => array(__('NO', 'hcode-addons') => '0', 
                           __('YES', 'hcode-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-29') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Youtube URL', 'hcode-addons' ),
          'param_name' => 'hcode_block_youtube_url',
          'dependency' => array( 'element' => 'hcode_block_youtube', 'value' => array('1') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'class' => '',
          'heading' => __('Show Linkedin Icon', 'hcode-addons'),
          'param_name' => 'hcode_block_linkedin',
          'value' => array(__('NO', 'hcode-addons') => '0', 
                           __('YES', 'hcode-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-29') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Linkedin URL', 'hcode-addons' ),
          'param_name' => 'hcode_block_linkedin_url',
          'dependency' => array( 'element' => 'hcode_block_linkedin', 'value' => array('1') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'class' => '',
          'heading' => __('Show Instagram Icon', 'hcode-addons'),
          'param_name' => 'hcode_block_instagram',
          'value' => array(__('NO', 'hcode-addons') => '0', 
                           __('YES', 'hcode-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-29') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Instagram URL', 'hcode-addons' ),
          'param_name' => 'hcode_block_instagram_url',
          'dependency' => array( 'element' => 'hcode_block_instagram', 'value' => array('1') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'class' => '',
          'heading' => __('Show Pinterest Icon', 'hcode-addons'),
          'param_name' => 'hcode_block_pinterest',
          'value' => array(__('NO', 'hcode-addons') => '0', 
                           __('YES', 'hcode-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-29') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Pinterest URL', 'hcode-addons' ),
          'param_name' => 'hcode_block_pinterest_url',
          'dependency' => array( 'element' => 'hcode_block_pinterest', 'value' => array('1') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'class' => '',
          'heading' => __('Show GitHub Icon', 'hcode-addons'),
          'param_name' => 'hcode_block_github',
          'value' => array(__('NO', 'hcode-addons') => '0', 
                           __('YES', 'hcode-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-29') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'GitHub URL', 'hcode-addons' ),
          'param_name' => 'hcode_block_github_url',
          'dependency' => array( 'element' => 'hcode_block_github', 'value' => array('1') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'class' => '',
          'heading' => __('Show Xing Icon', 'hcode-addons'),
          'param_name' => 'hcode_block_xing',
          'value' => array(__('NO', 'hcode-addons') => '0', 
                           __('YES', 'hcode-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-29') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Xing URL', 'hcode-addons' ),
          'param_name' => 'hcode_block_xing_url',
          'dependency' => array( 'element' => 'hcode_block_xing', 'value' => array('1') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'class' => '',
          'heading' => __('Show VK Icon', 'hcode-addons'),
          'param_name' => 'hcode_block_vk',
          'value' => array(__('NO', 'hcode-addons') => '0', 
                           __('YES', 'hcode-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-29') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'VK URL', 'hcode-addons' ),
          'param_name' => 'hcode_block_vk_url',
          'dependency' => array( 'element' => 'hcode_block_vk', 'value' => array('1') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'class' => '',
          'heading' => __('Show Website Icon', 'hcode-addons'),
          'param_name' => 'hcode_block_website',
          'value' => array(__('NO', 'hcode-addons') => '0', 
                           __('YES', 'hcode-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-29') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Website URL', 'hcode-addons' ),
          'param_name' => 'hcode_block_website_url',
          'dependency' => array( 'element' => 'hcode_block_website', 'value' => array('1') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'hcode_custom_switch_option',
          'class' => '',
          'heading' => __('Show Email Icon', 'hcode-addons'),
          'param_name' => 'hcode_block_email_address',
          'value' => array(__('NO', 'hcode-addons') => '0', 
                           __('YES', 'hcode-addons') => '1'
                          ),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-29') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Email Address', 'hcode-addons' ),
          'param_name' => 'hcode_block_email_address_url',
          'dependency' => array( 'element' => 'hcode_block_email_address', 'value' => array('1') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'textarea_raw_html',
          'heading' => __( 'Custom Icon & Link Code', 'hcode-addons' ),
          'param_name' => 'hcode_block_custom_link',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-29') ),
          'group'       => 'Other Settings',
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Title Font Size', 'hcode-addons' ),
          'description' => __( 'Define font size like 12px', 'hcode-addons' ),
          'param_name' => 'hcode_block_title_font_size',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-8','block-26') ),
          'group'       => 'Style',
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Title Line height', 'hcode-addons' ),
          'description' => __( 'Define line height like 20px', 'hcode-addons' ),
          'param_name' => 'hcode_block_title_line_height',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-8','block-26') ),
          'group'       => 'Style',
        ),
        array(
            'type' => 'dropdown',
            'heading' => __('Select Icon Size', 'hcode-addons'),
            'param_name' => 'hcode_block_icon_size',
            'value' => array(__('Default', 'hcode-addons') => '',
                             __('Extra Large', 'hcode-addons') => 'extra-large-icon', 
                             __('Large', 'hcode-addons') => 'large-icon',
                             __('Medium', 'hcode-addons') => 'medium-icon',
                             __('Small', 'hcode-addons') => 'small-icon',
                             __('Extra Small', 'hcode-addons') => 'extra-small-icon',
                            ),
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-2','block-13', 'block-20', 'block-24', 'block-30', 'block-31', 'block-32','block-55') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Border Color', 'hcode-addons' ),
            'param_name' => 'hcode_block_border_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-2','block-9','block-23','block-25','block-27','block-29','block-30','block-31','block-33','block-35','block-41','block-45') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Icon Color', 'hcode-addons' ),
            'param_name' => 'hcode_block_icon_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-2','block-13', 'block-20', 'block-24', 'block-30', 'block-31','block-32','block-36','block-37','block-54','block-55') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Title Text Color', 'hcode-addons' ),
            'param_name' => 'hcode_block_title_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-1','block-2','block-3','block-4','block-5','block-6','block-7','block-8','block-9','block-10','block-11','block-12','block-13','block-14','block-15','block-16','block-17','block-19', 'block-20', 'block-21', 'block-22','block-23', 'block-24','block-25','block-26','block-27','block-28','block-29', 'block-30', 'block-31','block-32', 'block-34','block-35','block-36','block-37','block-38','block-39','block-40','block-41','block-42','block-43','block-44', 'block-45', 'block-46', 'block-47', 'block-48','block-49','block-50','block-51','block-52','block-53','block-54','block-55') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'SubTitle Text Color', 'hcode-addons' ),
            'param_name' => 'hcode_block_subtitle_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-3','block-4','block-8','block-9','block-10','block-11','block-20','block-25','block-26','block-27','block-29','block-36','block-37','block-39', 'block-45', 'block-47','block-49','block-50') ),
            'group' => 'Style',
        ),
        array(
          'type' => 'textfield',
          'heading' => __('Separator Height', 'hcode-addons' ),
          'param_name' => 'separator_height',
          'dependency' => array( 'element' => 'hcode_block_show_separator', 'value' => array('1') ),
          'description' => __( 'Define custom separator height in px like 2px', 'hcode-addons' ),
          'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Separator Color', 'hcode-addons' ),
            'param_name' => 'hcode_sep_color',
            'dependency' => array( 'element' => 'hcode_block_show_separator', 'value' => array('1') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Number Color', 'hcode-addons' ),
            'param_name' => 'hcode_block_number_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-20','block-21', 'block-23','block-28','block-44', 'block-48') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Number Hover Color', 'hcode-addons' ),
            'param_name' => 'hcode_block_hover_number_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-23') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Number Background Color', 'hcode-addons' ),
            'param_name' => 'hcode_block_number_bg_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-21','block-28') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Price Color', 'hcode-addons' ),
            'param_name' => 'hcode_block_price_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-43') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Price Background Color', 'hcode-addons' ),
            'param_name' => 'hcode_block_price_bg_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-43') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Number Border Color', 'hcode-addons' ),
            'param_name' => 'hcode_block_number_border_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-21') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Discount Text Background Color', 'hcode-addons' ),
            'param_name' => 'hcode_block_dis_text_bg_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-9') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Discount Text Color', 'hcode-addons' ),
            'param_name' => 'hcode_block_dis_text_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-9') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Button Background Color', 'hcode-addons' ),
            'param_name' => 'hcode_block_button_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-6','block-38') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Button Text Color', 'hcode-addons' ),
            'param_name' => 'hcode_block_button_text_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-6','block-38') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Button Border Color', 'hcode-addons' ),
            'param_name' => 'hcode_block_button_border_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-6') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Button Arrow Color', 'hcode-addons' ),
            'param_name' => 'hcode_block_button_arrow_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-38') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Block Hover Title Color', 'hcode-addons' ),
            'param_name' => 'hcode_block_hover_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-20','block-49') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Block Hover Bg Color', 'hcode-addons' ),
            'param_name' => 'hcode_block_hover_bg_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-20') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Block Hover Bg Color', 'hcode-addons' ),
            'param_name' => 'hcode_block_hover_back_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-27','block-32','block-55') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Block Hover Text Color', 'hcode-addons' ),
            'param_name' => 'hcode_block_hover_text_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-32','block-55') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Block BackGround color', 'hcode-addons' ),
            'param_name' => 'hcode_block_bg_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-39','block-46','block-53') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Block Hover Icon Color', 'hcode-addons' ),
            'param_name' => 'hcode_block_hover_icon_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-32','block-49','block-55') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Block Hover Subtitle Color', 'hcode-addons' ),
            'param_name' => 'hcode_block_hover_subtitle_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-49') ),
            'group' => 'Style',
        ),
        array(
            'type' => 'colorpicker',
            'class' => '',
            'heading' => __( 'Block Hover Border Color', 'hcode-addons' ),
            'param_name' => 'hcode_block_hover_border_color',
            'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-23') ),
            'group' => 'Style',
        ),
        array(
          'type' => 'hcode_animation_style',
          'param_name' => 'hcode_animation_style',
          'heading' => __('Animation Style', 'hcode-addons' ),
          'value' => '',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-10') ),
          'group' => 'Animation',
        ),
        array(
          'type'        => 'hcode_button_settings',
          'param_name'  => 'button_one_config_settings',
          'heading'     => esc_html__( 'Button Configuration', 'hcode-addons' ),
          'group' => 'Button Configuration',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-1','block-4','block-6','block-18','block-30','block-37','block-39','block-42','block-45','block-49') ),
          'description' => __( 'You can easily set button text-transform, font-size, line-height, letter-spacing for all devices ', 'hcode-addons' ),
          'hide_font_settings_element'=>array('icon-color','icon-hover-color')
        ),
        array(
          'type'        => 'hcode_button_settings',
          'param_name'  => 'button_icon_config_settings',
          'heading'     => esc_html__( 'Button Configuration', 'hcode-addons' ),
          'group' => 'Button Configuration',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-2','block-38') ),
          'description' => __( 'You can easily set button text-transform, font-size, line-height, letter-spacing for all devices ', 'hcode-addons' ),
        ),
        array(
          'type'        => 'hcode_button_settings',
          'param_name'  => 'button_two_config_settings',
          'heading'     => esc_html__( 'Hover Button Configuration', 'hcode-addons' ),
          'group' => 'Button Configuration',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-49') ),
          'description' => __( 'You can easily set button text-transform, font-size, line-height, letter-spacing for all devices ', 'hcode-addons' ),
          'hide_font_settings_element'=>array('icon-color','icon-hover-color')
        ),
        array(
          'type'        => 'responsive_font_settings',
          'param_name'  => 'hcode_responsive_title_font',
          'heading'     => esc_html__( 'Font Settings For Title', 'hcode-addons' ),
          'hide_font_settings_element_lg' => array('text-align'),
          'hide_font_settings_element_md' => array('text-align'),
          'hide_font_settings_element_sm' => array('text-align'),
          'hide_font_settings_element_xs' => array('text-align'),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-1','block-2','block-3','block-4','block-5','block-6','block-7','block-8','block-9','block-10','block-11', 'block-12', 'block-13','block-14','block-15', 'block-16', 'block-17','block-19','block-20','block-21', 'block-22', 'block-23', 'block-24','block-25','block-26','block-27','block-28','block-29', 'block-30', 'block-31', 'block-32','block-34','block-35','block-36','block-37','block-38','block-39','block-40','block-41','block-42','block-43','block-44', 'block-45', 'block-46', 'block-47', 'block-48','block-49','block-50','block-51','block-52','block-53','block-54','block-55') ),
          'group' => 'Font Settings',
        ),
        array(
          'type'        => 'responsive_font_settings',
          'param_name'  => 'hcode_responsive_subtitle_font',
          'heading'     => esc_html__( 'Font Settings For Subtitle', 'hcode-addons' ),
          'hide_font_settings_element_lg' => array('text-align'),
          'hide_font_settings_element_md' => array('text-align'),
          'hide_font_settings_element_sm' => array('text-align'),
          'hide_font_settings_element_xs' => array('text-align'),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-3','block-4','block-8','block-9','block-10','block-11','block-20','block-25','block-26','block-27','block-29','block-36','block-37','block-39', 'block-45', 'block-47','block-49','block-50') ),
          'group' => 'Font Settings',
        ),
        array(
          'type'        => 'responsive_font_settings',
          'param_name'  => 'hcode_responsive_number_font',
          'heading'     => esc_html__( 'Font Settings For Number', 'hcode-addons' ),
          'hide_font_settings_element_lg' => array('text-align'),
          'hide_font_settings_element_md' => array('text-align'),
          'hide_font_settings_element_sm' => array('text-align'),
          'hide_font_settings_element_xs' => array('text-align'),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-20','block-21', 'block-23','block-28','block-44', 'block-48') ),
          'group' => 'Font Settings',
        ),
        array(
          'type'        => 'responsive_font_settings',
          'param_name'  => 'hcode_responsive_hover_title_font',
          'heading'     => esc_html__( 'Font Settings For Hover Title', 'hcode-addons' ),
          'hide_font_settings_element_lg' => array('text-align'),
          'hide_font_settings_element_md' => array('text-align'),
          'hide_font_settings_element_sm' => array('text-align'),
          'hide_font_settings_element_xs' => array('text-align'),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-20','block-49') ),
          'group' => 'Font Settings',
        ),
        array(
          'type'        => 'responsive_font_settings',
          'param_name'  => 'hcode_responsive_price_font',
          'heading'     => esc_html__( 'Font Settings For price', 'hcode-addons' ),
          'hide_font_settings_element_lg' => array('text-align'),
          'hide_font_settings_element_md' => array('text-align'),
          'hide_font_settings_element_sm' => array('text-align'),
          'hide_font_settings_element_xs' => array('text-align'),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-43') ),
          'group' => 'Font Settings',
        ),
        array(
          'type'        => 'responsive_font_settings',
          'param_name'  => 'hcode_responsive_dis_text_font',
          'heading'     => esc_html__( 'Font Settings For Discount Text', 'hcode-addons' ),
          'hide_font_settings_element_lg' => array('text-align'),
          'hide_font_settings_element_md' => array('text-align'),
          'hide_font_settings_element_sm' => array('text-align'),
          'hide_font_settings_element_xs' => array('text-align'),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-9') ), 
          'group' => 'Font Settings',
        ),
        array(
          'type'        => 'responsive_font_settings',
          'param_name'  => 'hcode_responsive_hover_subtitle_font',
          'heading'     => esc_html__( 'Font Settings For Hover Subtitle', 'hcode-addons' ),
          'hide_font_settings_element_lg' => array('text-align'),
          'hide_font_settings_element_md' => array('text-align'),
          'hide_font_settings_element_sm' => array('text-align'),
          'hide_font_settings_element_xs' => array('text-align'),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-49') ),
          'group' => 'Font Settings',
        ),
        array(
          'type'        => 'responsive_font_settings',
          'param_name'  => 'hcode_responsive_small_title_font',
          'heading'     => esc_html__( 'Font Settings For Small Title', 'hcode-addons' ),
          'hide_font_settings_element_lg' => array('text-align'),
          'hide_font_settings_element_md' => array('text-align'),
          'hide_font_settings_element_sm' => array('text-align'),
          'hide_font_settings_element_xs' => array('text-align'),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-50') ),
          'group' => 'Font Settings',
        ),
        array(
          'type'        => 'responsive_font_settings',
          'param_name'  => 'hcode_responsive_destinations_title_font',
          'heading'     => esc_html__( 'Font Settings For Destinations Title', 'hcode-addons' ),
          'hide_font_settings_element_lg' => array('text-align'),
          'hide_font_settings_element_md' => array('text-align'),
          'hide_font_settings_element_sm' => array('text-align'),
          'hide_font_settings_element_xs' => array('text-align'),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-50') ),
          'group' => 'Font Settings',
        ),
        array(
          'type'        => 'responsive_font_settings',
          'param_name'  => 'hcode_responsive_destinations_subtitle_font',
          'heading'     => esc_html__( 'Font Settings For Destinations Subtitle', 'hcode-addons' ),
          'hide_font_settings_element_lg' => array('text-align'),
          'hide_font_settings_element_md' => array('text-align'),
          'hide_font_settings_element_sm' => array('text-align'),
          'hide_font_settings_element_xs' => array('text-align'),
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-50') ),
          'group' => 'Font Settings',
        ),
        array(
          'type' => 'hcode_custom_srcset',
          'param_name' => 'hcode_image_srcset',
          'heading' => __('Image SRCSET', 'hcode-addons' ),
          'value' => 'full',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-1','block-4','block-5','block-7','block-18','block-19','block-22','block-25','block-26','block-27','block-29','block-33','block-34','block-35','block-36','block-37','block-39','block-40','block-42','block-43','block-44','block-49','block-50','block-51','block-53') ),
          'group' => 'SRCSET',
        ),
        array(
          'type' => 'hcode_custom_srcset',
          'param_name' => 'hcode_icon_image_srcset',
          'heading' => __('Icon Image SRCSET', 'hcode-addons' ),
          'value' => 'full',
          'dependency' => array( 'element' => 'custom_icon', 'value' => '1' ),
          'group' => 'SRCSET',
        ),
        array(
          'type' => 'hcode_custom_srcset',
          'param_name' => 'hcode_hover_icon_image_srcset',
          'heading' => __('Custom Hover Icon1 Image SRCSET', 'hcode-addons' ),
          'value' => 'full',
          'dependency' => array( 'element' => 'hcode_block_hover_custom_icon', 'value' => '1' ),
          'group' => 'SRCSET',
        ),
        array(
          'type' => 'hcode_custom_srcset',
          'param_name' => 'hcode_hover_icon2_image_srcset',
          'heading' => __('Custom Hover Icon2 Image SRCSET', 'hcode-addons' ),
          'value' => 'full',
          'dependency' => array( 'element' => 'hcode_block_hover_custom_icon2', 'value' => '1' ),
          'group' => 'SRCSET',
        ),
        array(
          'type' => 'hcode_custom_srcset',
          'param_name' => 'hcode_destinations_image_srcset',
          'heading' => __('Destinations Image SRCSET', 'hcode-addons' ),
          'value' => 'full',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-50') ),
          'group' => 'SRCSET',
        ),
        array(
          'type' => 'hcode_custom_srcset',
          'param_name' => 'hcode_destinations_image2_srcset',
          'heading' => __('Destinations Image2 SRCSET', 'hcode-addons' ),
          'value' => 'full',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-50') ),
          'group' => 'SRCSET',
        ),
        array(
          'type' => 'hcode_custom_srcset',
          'param_name' => 'hcode_destinations_image3_srcset',
          'heading' => __('Destinations Image3 SRCSET', 'hcode-addons' ),
          'value' => 'full',
          'dependency' => array( 'element' => 'hcode_block_premade_style', 'value' => array('block-50') ),
          'group' => 'SRCSET',
        ),
        $hcode_vc_extra_id,
        $hcode_vc_extra_class,
      )
    ) );